apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftingapp-deployment
  labels:
    app: giftingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: giftingapp
  template:
    metadata:
      labels:
        app: giftingapp
    spec:
      containers:
      - name: merchant
        image: attesteph/merchant-0.0.1
        ports:
        - name: merchant-port
          containerPort: 8081
      - name: shopping
        image: attesteph/shopping-0.0.1
        ports:
        - name: shopping-port
          containerPort: 8081
