apiVersion: v1
kind: Service
metadata:
  name: giftingapp-service
spec:
  selector:
    app: giftingapp
  ports:
  - name: merchant-port
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: shopping-port
    protocol: TCP
    port: 8082
